name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  check:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: actionlint
            run: actionlint
          - name: lua_ls
            run: lua-language-server --check=. --checklevel=Warning
          - name: prettier
            run: prettier --check --ignore-unknown .
          - name: shellcheck
            run: shfmt --find . | xargs -r shellcheck --severity=style --exclude=SC1071
          - name: shfmt
            run: shfmt --diff .
          - name: stylua
            run: stylua --check .
          - name: taplo
            run: taplo format --check
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - run: ${{ matrix.run }}
